### ISSUE TITLE
Error even while trying to initialize Airgram

### ISSUE THREAD

**Issue by syedareehaquasar** [airgram/airgram-js-example#14]
```throw new Error('Dynamic Linking Error: ' + err);
          ^

Error: Dynamic Linking Error: Win32 error 126
    at new DynamicLibrary (E:\SocioCLub\node_modules\ffi-napi\lib\dynamic_library.js:75:11)
    at Object.Library (E:\SocioCLub\node_modules\ffi-napi\lib\library.js:47:10)
    at new TdJsonClient (E:\SocioCLub\node_modules\airgram\components\TdJsonClient.js:86:27)
    at new Airgram (E:\SocioCLub\node_modules\airgram\Airgram.js:50:116)
    at file:///E:/SocioCLub/index.js:41:17
    at ModuleJob.run (internal/modules/esm/module_job.js:169:25)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

Tried cloning the repo and running as well and I am getting failure msg
```#
# Fatal error in , line 0
# Check failed: result.second.
#
#
#
#FailureMessage Object: 000000CACAD8AC20
```

Can someone help me out!

**Comment by NeetishRaj** [comment]
Facing the same problem myself
```
node - v16.14.0
airgram - v5.0.0
OS: Windows 10
```

Error message:
```
PS D:\work\TelegramBot\NodejsTelegramClient> node index.js
D:\work\TelegramBot\NodejsTelegramClient\node_modules\ffi-napi\lib\dynamic_library.js:75
    throw new Error('Dynamic Linking Error: ' + err);
    ^

Error: Dynamic Linking Error: Win32 error 126
    at new DynamicLibrary (D:\work\TelegramBot\NodejsTelegramClient\node_modules\ffi-napi\lib\dynamic_library.js:75:11)
    at Object.Library (D:\work\TelegramBot\NodejsTelegramClient\node_modules\ffi-napi\lib\library.js:47:10)    
    at new TdJsonClient (D:\work\TelegramBot\NodejsTelegramClient\node_modules\airgram\components\TdJsonClient.js:112:28)
    at new Airgram (D:\work\TelegramBot\NodejsTelegramClient\node_modules\airgram\Airgram.js:51:116)
    at Object.<anonymous> (D:\work\TelegramBot\NodejsTelegramClient\index.js:11:17)
```

**Comment by syedareehaquasar** [comment]
I switched to wsl and tried worked for me you can try shifting to any Linux based environment as well if it's urgent @neetishraj

**Comment by javierarocena** [comment]
Same error  here...

![image](https://user-images.githubusercontent.com/33159867/166268652-34fff9f5-1998-4147-b91e-8b8144c38144.png)

**Comment by NeetishRaj** [comment]
> I switched to wsl and tried worked for me you can try shifting to any Linux based environment as well if it's urgent @NeetishRaj

No luck even in WSL for me. Had to use Python for my use

**Comment by lakshmankashyap** [comment]
It works for me when i change airgram version 5.0.0
