### ISSUE TITLE
Error: ENOENT: no such file or directory, open tdlib/libtdjson.so 

### ISSUE THREAD

**Issue by FabioNevesRezende** [airgram/airgram-js-example#7]
After cloning repo and following readme instructions, program fails after `npm run dev`:

> airgram-js-example@0.0.0 dev
> DEBUG=airgram* dotenv -e .env nodemon --config nodemon.json

```
[nodemon] 1.18.9
[nodemon] reading config ./nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 42855 to restart
[nodemon] watching: ./src/**/*.js
[nodemon] watching extensions: js
[nodemon] starting `node src/index.js`
[nodemon] spawning
[nodemon] child pid: 42867
[nodemon] watching 1 file
node:internal/fs/utils:323
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/src/airgram-js-example/tdlib/libtdjson.so'
    at Object.openSync (node:fs:505:3)
    at readFileSync (node:fs:401:35)
    at new DynamicLibrary (/src/airgram-js-example/node_modules/ffi-napi/lib/dynamic_library.js:68:23)
    at Object.Library (/src/airgram-js-example/node_modules/ffi-napi/lib/library.js:47:10)
    at new TdJsonClient (/src/airgram-js-example/node_modules/airgram/components/TdJsonClient.js:86:27)
    at new Airgram (/src/airgram-js-example/node_modules/airgram/Airgram.js:50:116)
    at Object.<anonymous> (/src/airgram-js-example/src/index.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/src/airgram-js-example/tdlib/libtdjson.so'
}
[nodemon] app crashed - waiting for file changes before starting...

```

npm --version
7.7.6
"airgram": "^3.3.0"

**Comment by stav** [comment]
cp  tdlib/td/build/libtdjson.so.1.7.9  airgram/examples/getting-started/libtdjson.so
